# Generated by Django 3.2.8 on 2022-12-02 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contact',
        ),
    ]
